### ISSUE TITLE
Skittle Color Calibration

### ISSUE THREAD

**Issue by isomorphic85** [CharmySoft/skittle-color-sorter#2]
I'm trying to calibrate the individual skittle colors ... however when I look at the values under #define COLORS_DEFINITION  

the calibrated and color view colors are not in the same format that i'm seeing in the serial monitor utilizing your 

Serial.print("c value is: "); Serial.println(c);  

I'm sure it's something i'm doing wrong , but have not been able to figure out what my mistake is.

When I run the above serial.print line I just get a single number such as 240 , I do see this number change as I run different colored skittles through it but i'm not sure how to edit the color definition numbers utilizing the single numbers that come through .

Please point me in the right direction.

Thanks again for all your help on this....

**Comment by yumin-chen** [comment]
Hi,

In the color definition macro, the colors are defined using the [C_Color class](https://github.com/CharmySoft/skittle-color-sorter/blob/0e35eeb5e8162300565f55348b2329787d5cfc22/c_color.h#L26) whose constructor takes RGBC (red, green, blue, clear) as arguments.

The number you were getting with the following line of code is only the clear light sensing value.

```
Serial.print("c value is: "); Serial.println(c);
```

If you want to print the RGBC values, you can either manually print them using

```
Serial.print("r value is: "); Serial.println(r);
Serial.print("g value is: "); Serial.println(g);
Serial.print("b value is: "); Serial.println(b);
Serial.print("c value is: "); Serial.println(c);
```

Or if you have the C_Color object, you can just go `C_Color::print();`
You can try putting this line below this [C_Color object](https://github.com/CharmySoft/skittle-color-sorter/blob/0e35eeb5e8162300565f55348b2329787d5cfc22/ColorSensor.cpp#L60) and it'll print the colors for you.

```
colors.print();
```

However, there's a better way to get the color definition of your Skittles. 
If you've picked a reasonable [C_HOLE_CLEAR](https://github.com/CharmySoft/skittle-color-sorter/blob/0e35eeb5e8162300565f55348b2329787d5cfc22/ColorSensor.cpp#L19) value that can distinguish when Skittles are at the color sensor. You can just set the calibration flags as follows: 

```
// Change the following line to enter calibration mode
#define F_CALIBRATING             true         /**< Is calibration in progress */
#define F_CALI_EMPTY_HOLE         false         /**< Is calibrating the empty hole's color */
```

This should allow you to enter calibration mode and the colors will be printed onto the Serial from [here](https://github.com/CharmySoft/skittle-color-sorter/blob/96916636a097fbf21fdb3f6c7abc4d862dfae875/ColorSensor.cpp#L123).

**Comment by isomorphic85** [comment]
Thank you for taking the time to help out!  

I will try giving this a try later tonight when I get home.

Hopefully this will resolve the calibration problem i'm experiencing (which is user error) 

as far as the actual feed wheel for the skittles does there need to be any specific color difference where the empty hole would be?

for example my entire feed wheel is printed in black, the empty hole of the feed wheel is also black. Is this ok or should I change the color of the empty hole to be say white?

**Comment by ghost** [comment]
The color sensor should be able to pick up the difference as there will be be less lighting in the "empty hole", thus the smaller clear value.
